import { StyleSheet } from "react-native";
import { Color, Dimension, FontFamily, FontSize, Padding } from "../../enums";

const styles = StyleSheet.create({
  headerContainer: {
    backgroundColor: "#fff",
    paddingHorizontal: "3%",
  },
  mainView: {
    marginLeft: "1%",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
  },
  drawerIconSection: {
    justifyContent: "center",
    alignItems: "center",
  },
  drawerIcon: {
    height: 60,
    width: 60,
    resizeMode: "contain",
  },
  profileImgView: {
    justifyContent: "center",
    alignItems: "center",
  },
  profileImg: {
    height: 30,
    width: 30,
    resizeMode: "contain",
    marginRight: 2,
  },
  headerMiddleSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingHorizontal: "2%",
  },
  headerText: {
    textAlign: "center",
    fontFamily: FontFamily.FONTS.INTER.BOLD,
    fontSize: FontSize.MD,
    color: Color.COLOR.BLACK.PURE_BLACK,
  },
  otherItemCircle: {
    width: 35,
    height: 35,
    borderRadius: 60,
    justifyContent: "center",
    alignItems: "center",
    marginRight: "5%",
  },
  notiCountText: {
    color: Color.COLOR.WHITE.PURE_WHITE,
    fontSize: 8,
    fontFamily: FontFamily.FONTS.INTER.LIGHT,
  },
  notificationSec: {
    width: 30,
    height: 30,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyCircle: {
    width: 18,
    height: 18,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    right: 12,
    top: -7,
  },
  countCircle: {
    top: 0,
    right: 0,
    position: "absolute",
    width: 18,
    height: 18,
    borderRadius: 30,
    backgroundColor: Color.COLOR.RED.PURE_RED,
    justifyContent: "center",
    alignItems: "center",
  },
  notiCircle: {
    width: 18,
    height: 18,
    borderRadius: 30,
    // backgroundColor: Color.COLOR.RED.PURE_RED,
    justifyContent: "center",
    alignItems: "center",
    right: 12,
    top: -7,
  },
  logoImg: {
    width: 28,
    height: 28,
    resizeMode: "contain",
    borderRadius: 20,
  },

  // ....modal,,,,,
  modalview: {
    backgroundColor: "#fff",
    marginRight: "5%",
    marginLeft: "5%",
    // paddingTop: 40,
    paddingBottom: 30,
    borderRadius: 10,
  },
  modalMainView: {
    marginLeft: "5%",
    marginRight: "5%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
  },
  crossCircelView: {
    height: 40,
    width: 40,
    borderRadius: 25,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#8D8D8D",
    borderWidth: 1,
  },
  redCrossImage: {
    height: 30,
    width: 30,
    resizeMode: "contain",
  },
  attendanceHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  attendanceHeaderText: {
    marginLeft: 10,
    fontSize: FontSize.SM,
    color: Color.COLOR.BLUE.VIOLET_BLUE,
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  attendanceBody: {
    marginTop: 10,
  },
  underline: {
    marginVertical: 5,
    height: 1,
    borderColor: Color.COLOR.BLUE.VIOLET_BLUE,
    backgroundColor: Color.COLOR.BLUE.VIOLET_BLUE,
    borderWidth: 1,
    width: "100%",
  },
  attendanceBodyText: {
    fontWeight: "600",
    fontSize: FontSize.SM,
    color: Color.COLOR.BLACK.BLACK_PEARL,
    fontFamily: FontFamily.FONTS.INTER.LIGHT,
  },
  attendanceButton: {
    alignItems: "flex-end",
    flexDirection: "row",
    marginTop: 15,
  },
  yesBtn: {
    fontSize: 16,
    color: "#1b679e",
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  noBtn: {
    fontSize: FontSize.MD,
    color: Color.COLOR.BLUE.LAPIS_LAZULI,
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  yesBtnMain: {
    marginLeft: 10,
    borderWidth: 0.5,
    elevation: 2,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderColor: Color.COLOR.GRAY.LIGHT_GRAY_COLOR,
    backgroundColor: Color.COLOR.WHITE.PURE_WHITE,
    borderRadius: 10,
  },
  noBtnMain: {
    marginRight: 10,
    borderWidth: 0.5,
    elevation: 2,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderColor: Color.COLOR.GRAY.LIGHT_GRAY_COLOR,
    backgroundColor: Color.COLOR.WHITE.PURE_WHITE,
    borderRadius: 10,
  },
  congratulationTxt: {
    // fontSize: 22
    fontSize: FontSize.MD,
    color: Color.COLOR.BLUE.LAPIS_LAZULI,
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  congratulationFooterTxt: {
    fontSize: 18,
    textAlign: "center",
    color: Color.COLOR.BLUE.LAPIS_LAZULI,
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  attendanceSuccessBody: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
  },
  okMainBtn: {
    borderRadius: 10,
    borderColor: "#000305",
    borderStyle: "solid",
    marginTop: 20,
  },
  okBtn: {
    fontSize: 16,
    color: Color.COLOR.BLUE.LAPIS_LAZULI,
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  tooltipListView: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderColor: Color.COLOR.GRAY.GRAY_COLOR,
    borderBottomWidth: 0.5,
  },
  tooltipText: {
    fontFamily: FontFamily.FONTS.INTER.MEDIUM,
    color: Color.COLOR.BLACK.PURE_BLACK,
    fontSize: FontSize.SM,
  },
  yesBtnok: {
    // marginTop:10,
    fontSize: 16,
    color: Color.COLOR.WHITE.PURE_WHITE,
    fontFamily: FontFamily.FONTS.INTER.BOLD,
  },
  yesBtnMainOk: {
    marginLeft: 10,
    marginTop: 15,
    borderWidth: 0.5,
    elevation: 2,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderColor: Color.COLOR.GRAY.LIGHT_GRAY_COLOR,
    backgroundColor: Color.COLOR.BLUE.VIOLET_BLUE,
    borderRadius: 10,
  },

  notiIconBackCircle: {
    padding: 5,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    backgroundColor: "#fff",
    marginRight: "1%",
  },
  menuModalMainView: {
    top: "4%",
    position: "absolute",
    right: "1%",
    width: Dimension.width / 1.3,
    height: Dimension.height / 6,
    backgroundColor: "#fff",
    elevation: 5,
    borderRadius: 16,
  },
  modalProfileName: {
    fontFamily: FontFamily.FONTS.INTER.MEDIUM,
    fontSize: FontSize.MD,
    color: "#6D6E7B",
  },
  homeText: {
    fontFamily: FontFamily.FONTS.INTER.MEDIUM,
    fontSize: FontSize.MD,
    color: "#ffffff",
  },
  workDetailsItemText: {
    fontFamily: FontFamily.FONTS.INTER.MEDIUM,
    fontSize: FontSize.SM,
    color: "#706F83",
  },

  eachLineSection: {
    flexDirection: "row",
    marginTop: 20,
    alignItems: "center",
  },
  profileImgMainView: {
    height: 80,
    width: 80,
    borderRadius: 50,
    backgroundColor: "red",
    alignItems: "center",
    justifyContent: "center",
  },
  profilePic: {
    height: 80,
    width: 80,
    resizeMode: "stretch",
    borderRadius: 50,
  },
  profileNameMainView: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: "5%",
  },
  selectedSectionView: {
    height: 60,
    borderRadius: 30,
    width: "100%",
    backgroundColor: "#3067C4",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: "10%",
  },
  notSelectedView: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: "10%",
  },
  liveGreenCircel: {
    height: 22,
    width: 22,
    borderRadius: 100,
    backgroundColor: "#7ED887",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "20%",
  },
  deepGreenCircel: {
    position: "absolute",
    height: 12,
    width: 12,
    borderRadius: 100,
    backgroundColor: "#00710C",
    left: 25,
    top: -5,
  },
  auctionCrossTab: {
    justifyContent: "center",
    alignItems: "center",
  },
  auctionCrossImg: {
    height: 20,
    width: 20,
    resizeMode: "contain",
  },
  changePassPressSec: {
    flexDirection: "row",
    marginTop: 20,
  },
  greyChangePassImgSec: {
    justifyContent: "center",
    alignItems: "center",
  },
  greyChangePassImg: {
    height: 25,
    width: 25,
    resizeMode: "contain",
  },
  changePassTxtSec: {
    flex: 1,
    marginLeft: "10%",
    justifyContent: "center",
  },
});

export default styles;
